version: '3.8'

services:
  frontend:
    build:
      context: ./inventory-manager-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./inventory-manager
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=t8ltavvRLd
    depends_on:
      - database 
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "database", "-p", "5432"]
      interval: 10s
      retries: 5

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: t8ltavvRLd
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
