version: '3.8'

services:

  postgres:
    image: postgres
    container_name: postgres_product
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: t8ltavvRLd
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data